import { CheckBox, StandardListView } from "std-widgets.slint";
import {
    AboutPage,
    SetupPage,
    ProjectsPage,
    UtilitiesPage,
} from "pages/pages.slint";
import { SideBar } from "side_bar.slint";
export { SetupPageLogic, Bs2Config } from "globals.slint";


export component App inherits Window {
    in property <bool> setup-done;
    min-width: 600px;
    preferred-width: 960px;
    min-height: 540px;
    title: @tr("BS2");
    icon: @image-url("../../../assets/icon.png");

    HorizontalLayout {
        visible: true;
        side-bar := SideBar {
            title: @tr("Bevy ↔ Source 2");
            model: [
                {
                    text: @tr("Menu" => "Installation"),
                    enabled: true,
                },
                {
                    text: @tr("Menu" => "Projects"),
                    enabled: setup-done,
                },
                {
                    text: @tr("Menu" => "Utilities"),
                    enabled: setup-done,
                },
                {
                    text: @tr("Menu" => "About"),
                    enabled: true,
                }
            ];
        }

        if(side-bar.current-item == 0): SetupPage {
            setup-done: setup-done;
        }
        if(side-bar.current-item == 1): ProjectsPage { }
        if(side-bar.current-item == 2): UtilitiesPage { }
        if(side-bar.current-item == 3): AboutPage { }
    }
}
