export enum Cs2State {
    None,
    GameOnly,
    Good
}


export global SetupPageLogic {
    callback run-setup();
    callback update-cs2-state();
    callback pick-cs2(string);
    in property <Cs2State> cs2-state;
    in property <string> copied_thing;
    in property <string> toast;
    in-out property <string> cs2-path;
    in property <bool> toast_error;
    in property <float> progress;
}

export struct ProjectDef {
    name: string,
    path: string,
}

export global ProjectsPageLogic {
    callback pick-project(string);
    callback launch-tools(string);
    callback update-project-selection();
    pure callback read-project(string) -> ProjectDef;
    callback create-project();
    in-out property <[string]> project-selection: ["foo", "bar"];
    in-out property <string> new-project-name;
    in-out property <string> new-project-path;
}

export global Bs2Config {
    callback write-config;
    in-out property <string> cs2_path;
    changed cs2_path => self.write-config();
    in-out property <int> last_project;
    changed last_project => self.write-config();
}
