export global SetupPageLogic {
    callback run-setup();
    callback update-cs2-state();
    callback pick-cs2;
    callback write-config;
    in property <string> cs2-state: "none";
    in property <string> copied_thing;
    in property <string> toast;
    in-out property <string> cs2-path;
    in property <bool> toast_error;
    in property <float> progress;
}

export struct ProjectDef {
    name: string,
    path: string,
}

export global ProjectsPageLogic {
    callback pick-project() -> string;
    in-out property <ProjectDef> new-project;
    in-out property <[ProjectDef]> projects: [{ name: "foo", path: "bar" }];
}

export global Bs2Config {
    in-out property <string> cs2_path;
    changed cs2_path => SetupPageLogic.write-config();
}
