import {
    Button,
    GroupBox,
    SpinBox,
    ComboBox,
    CheckBox,
    LineEdit,
    TabWidget,
    VerticalBox,
    HorizontalBox,
    Slider,
    ProgressIndicator,
    SpinBox,
    Switch,
    Spinner,
    GridBox,
    TimePickerPopup,
    DatePickerPopup,
    Palette,
    ListView,
    StandardButton,
} from "std-widgets.slint";
import { Page } from "page.slint";
import { ProjectsPageLogic, ProjectDef } from "../globals.slint";


export component ProjectsPage inherits Page {
    title: @tr("Projects");
    description: @tr("This page gives an overview of the default widget set provided by Slint. The widgets are available in different styles native, fluent-(dark/light) and material-(dark/light). The widgets can be imported from \"std-widgets.slint\".");

    VerticalBox {
        alignment: start;
        Text {
            text: "Manage your projects and launch the Source 2 Tools. If you need help setting up the Bevy side of things, see the guide.";
        }

        HorizontalBox {
            alignment: start;
            Text {
                vertical-alignment: center;
                horizontal-alignment: right;
                text: "Project:";
            }

            project-box := ComboBox {
                model <=> ProjectsPageLogic.project-selection;
                current-index <=> ProjectsPageLogic.project-idx;
            }
        }

        if project-box.current-index == 0: GroupBox {
            title: "New Project";

            VerticalBox {
                alignment: start;

                GridLayout {
                    Row {
                        Text {
                            text: "Directory:";
                            vertical-alignment: center;
                            horizontal-alignment: right;
                        }

                        Rectangle {
                            background: Palette.background;
                            HorizontalLayout {
                                LineEdit {
                                    text <=> ProjectsPageLogic.new-project-path;
                                    placeholder-text: "Path to the project root containing Cargo.toml";
                                    accepted => {
                                    }
                                    horizontal_stretch: 1;
                                }

                                Button {
                                    text: "📂";
                                    clicked => {
                                        ProjectsPageLogic.pick-project(ProjectsPageLogic.new-project-path);
                                    }
                                }
                            }
                        }
                    }

                    Row {
                        Text {
                            text: "Name:";
                            vertical-alignment: center;
                            horizontal-alignment: right;
                        }

                        Rectangle {
                            background: Palette.background;

                            HorizontalLayout {
                                LineEdit {
                                    text <=> ProjectsPageLogic.new-project-name;
                                    placeholder-text: "project_name";
                                    accepted => {
                                        create-btn.clicked()
                                    }
                                    horizontal_stretch: 1;
                                }
                            }
                        }
                    }
                }

                create-btn := Button {
                    text: "Create";
                    clicked => {
                        ProjectsPageLogic.create-project();
                        ProjectsPageLogic.update-project-selection();
                        let total = ProjectsPageLogic.project-selection;
                        ProjectsPageLogic.project-idx = total.length - 1;
                    }
                }
            }
        }

        if project-box.current-index >= 1: GroupBox {
            title: project-box.current-value;
            VerticalBox {
                HorizontalBox {
                    alignment: start;
                    Text {
                        text: "Path:";
                        vertical-alignment: center;
                        horizontal-alignment: right;
                    }

                    Text {
                        text: ProjectsPageLogic.read-project(project-box.current-value).path;
                        vertical-alignment: center;
                        horizontal-alignment: right;
                    }
                }

                Button {
                    text: "Launch Tools";
                    clicked => {
                        ProjectsPageLogic.launch-tools(project-box.current-value)
                    }
                }
            }
        }
    }

    Rectangle { }
}
