import {
    Button,
    GroupBox,
    SpinBox,
    ComboBox,
    CheckBox,
    LineEdit,
    TabWidget,
    VerticalBox,
    HorizontalBox,
    Slider,
    ProgressIndicator,
    SpinBox,
    Switch,
    Spinner,
    GridBox,
    TimePickerPopup,
    DatePickerPopup,
    TextEdit,
    Palette,
} from "std-widgets.slint";
import { Page } from "page.slint";

import { SetupPageLogic } from "../globals.slint";

export component SetupPage inherits Page {
    in property <bool> setup-done;
    title: @tr("Installation");
    description: @tr("This page gives an overview of the default widget set provided by Slint. The widgets are available in different styles native, fluent-(dark/light) and material-(dark/light). The widgets can be imported from \"std-widgets.slint\".");

    Text {
        wrap: word-wrap;
        text: setup-done ? "Whenever Counter Strike 2 updates, you can click on \"Update\" below to upgrade your installed Source 2 Tools" : "Before you can use BS2, you need to perform a one-time setup. This will copy the Source 2 Tools from an existing Counter Strike 2 installation into the install directory of BS2 and configure them to work with Bevy.\nFor this to work, you first need to manually install Counter Strike 2 with Workshop enabled. Follow the BS2 setup guide to find out how.";
    }

    GroupBox {
        title: "Counter Strike 2 Path";
        height: 120px;
        VerticalBox {
            alignment: start;
            height: 100px;

            path := LineEdit {
                text: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Counter-Strike Global Offensive\\";
            }
        }
    }

    Button {
        height: 40px;
        text: root.setup-done ? "Update" : "Install";
        clicked => {
            SetupPageLogic.setup(path.text)
        }
    }

    Rectangle { }
}
