import {
    Button,
    GroupBox,
    SpinBox,
    ComboBox,
    CheckBox,
    LineEdit,
    TabWidget,
    VerticalBox,
    HorizontalBox,
    Slider,
    ProgressIndicator,
    SpinBox,
    Switch,
    Spinner,
    GridBox,
    TimePickerPopup,
    DatePickerPopup,
    TextEdit,
    Palette,
} from "std-widgets.slint";
import { Page } from "page.slint";
import { SetupPageLogic } from "../globals.slint";


export component SetupPage inherits Page {
    in property <bool> setup-done;

    title: @tr("Installation");
    description: @tr("This page gives an overview of the default widget set provided by Slint. The widgets are available in different styles native, fluent-(dark/light) and material-(dark/light). The widgets can be imported from \"std-widgets.slint\".");

    Text {
        wrap: word-wrap;
        text: setup-done ? "Whenever Counter Strike 2 updates, you can click on \"Update\" below to upgrade your installed Source 2 Tools" : "Before you can use BS2, you need to perform a one-time setup. This will copy the Source 2 Tools from an existing Counter Strike 2 installation into the install directory of BS2 and configure them to work with Bevy.\nFor this to work, you first need to manually install Counter Strike 2 with Workshop enabled. Follow the BS2 setup guide to find out how.";
    }

    HorizontalBox {
        Text {
            text: "Counter Strike 2 Path:";
            vertical-alignment: center;
            horizontal-alignment: right;
        }

        HorizontalLayout {
            path := LineEdit {
                text <=> SetupPageLogic.cs2-path;
                accepted => {
                    SetupPageLogic.run-setup(SetupPageLogic.cs2-path)
                }
                horizontal_stretch: 1;
            }

            open_button := Button {
                text: "📂";
                clicked => {
                    SetupPageLogic.pick-cs2()
                }
            }
        }
    }

    Button {
        height: 40px;
        text: root.setup-done ? "Update" : "Install";
        clicked => {
            SetupPageLogic.run-setup(SetupPageLogic.cs2-path)
        }
    }

    Rectangle { }
}
