import {
    Button,
    GroupBox,
    SpinBox,
    ComboBox,
    CheckBox,
    LineEdit,
    TabWidget,
    VerticalBox,
    HorizontalBox,
    Slider,
    ProgressIndicator,
    SpinBox,
    Switch,
    Spinner,
    GridBox,
    TimePickerPopup,
    DatePickerPopup,
    TextEdit,
    Palette,
} from "std-widgets.slint";
import { Page } from "page.slint";
import { SetupPageLogic, Bs2Config } from "../globals.slint";


export component SetupPage inherits Page {
    in property <bool> setup-done;

    title: @tr("Installation");
    description: @tr("This page gives an overview of the default widget set provided by Slint. The widgets are available in different styles native, fluent-(dark/light) and material-(dark/light). The widgets can be imported from \"std-widgets.slint\".");

    Text {
        wrap: word-wrap;
        text: setup-done ? "Whenever Counter Strike 2 updates, you can click on \"Update\" below to upgrade your installed Source 2 Tools" : "Before you can use BS2, you need to perform a one-time setup. This will copy the Source 2 Tools from an existing Counter Strike 2 installation into the install directory of BS2 and configure them to work with Bevy.\nFor this to work, you first need to manually install Counter Strike 2 with Workshop enabled. Follow the BS2 setup guide to find out how.";
    }

    HorizontalBox {
        Text {
            text: "Counter Strike 2 directory:";
            vertical-alignment: center;
            horizontal-alignment: right;
        }

        Rectangle {
            background: SetupPageLogic.copied_thing != "" ? Palette.background : SetupPageLogic.cs2-state == "good" ? green.with-alpha(0.2) : SetupPageLogic.cs2-state == "only-game" ? orange.with-alpha(0.2) : red.with-alpha(0.2);
            HorizontalLayout {
                LineEdit {
                    enabled: SetupPageLogic.copied_thing == "";
                    text <=> SetupPageLogic.cs2-path;
                    accepted => {
                        if SetupPageLogic.cs2-state == "good" {
                            SetupPageLogic.run-setup()
                        }
                    }
                    changed text => {
                        SetupPageLogic.update-cs2-state();
                        if SetupPageLogic.cs2-state == "good" {
                            Bs2Config.cs2_path = SetupPageLogic.cs2-path;
                        }
                    }
                    horizontal_stretch: 1;
                }

                open_button := Button {
                    text: "📂";
                    enabled: SetupPageLogic.copied_thing == "";
                    clicked => {
                        SetupPageLogic.pick-cs2()
                    }
                }
            }
        }
    }

    if SetupPageLogic.cs2-state == "none": Text {
        text: "Counter Strike 2 is not installed at the above location. Consult the guide.";
        color: red.with-alpha(0.7);
    }

    if SetupPageLogic.cs2-state == "only-game": Text {
        text: "Counter Strike 2 is installed at the above location, but the Workshop has not been enabled. Consult the guide.";
        color: orange.with-alpha(0.7);
    }

    if SetupPageLogic.copied_thing != "": VerticalBox {
        alignment: start;
        Text {
            text: "Copying \{SetupPageLogic.copied_thing}...";
        }

        ProgressIndicator {
            progress: SetupPageLogic.progress;
        }
    }
    if SetupPageLogic.toast != "": VerticalBox {
        alignment: start;
        Text {
            text: SetupPageLogic.toast;
            color: SetupPageLogic.toast_error ? red : green;
        }
    }

    Button {
        height: 40px;
        text: root.setup-done ? "Update" : "Install";
        enabled: SetupPageLogic.cs2-state == "good" && SetupPageLogic.copied_thing == "";
        clicked => {
            SetupPageLogic.run-setup()
        }
    }

    Rectangle { }
}
