import {
    Button,
    GroupBox,
    SpinBox,
    ComboBox,
    CheckBox,
    LineEdit,
    TabWidget,
    VerticalBox,
    HorizontalBox,
    Slider,
    ProgressIndicator,
    SpinBox,
    Switch,
    Spinner,
    GridBox,
    TimePickerPopup,
    DatePickerPopup,
} from "std-widgets.slint";
import { Page } from "page.slint";

export component UtilitiesPage inherits Page {
    title: @tr("Utilities");
    description: @tr("This page gives an overview of the default widget set provided by Slint. The widgets are available in different styles native, fluent-(dark/light) and material-(dark/light). The widgets can be imported from \"std-widgets.slint\".");
}
